; By default, core appears beyond 16:9.  Setting applies a 4:3 aspect ratio.
; Tested by TheJesusFish 20260430

; Full Name	DV1 Name
; Panasonic 3DO 3DO

[dv1]

detect.name = 3DO
map.ar = 4/3
map.ar.skip_auto2 = yes