[main]
orig_preset_name = PCE TG16 FILL
display_name = PCE TG16 FILL
description = Description can go here
tags = pce, tg16, auto-sample
; orig_feature_mask = 0x0500000f

[scaler]
zoom_factor = fill
aspect_ratio = auto
horiz_kernel = sharper
vert_kernel = sharper
nn_auto_mode = on

[auto-sample]
context = *
expected = 4,+11,+0,+0,+0,128/105,-
expected = 6,-6,+0,+0,+0,341/280,-
expected = 8,-1,+0,+0,+0,128/105,-
method = 1
threshold = -1

[analog]
sync.sog_lpf_sel = 1
sync.sog_threshold = 11
sync.separator_threshold = 68
sync.h_pll_pre_coast = 1
sync.h_pll_post_coast = 0
sync.line_length_tolerance = 6
sync.vs_bypass = 0

[fingerprint]
name = sys:240NTSCp
fingerprint = 15.7+0.2,262+2,0,-,-,-,-,-
settings = 1716,1280,240,392,18,4/3,4,0/1,-1,0.0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,16,16,16,1,11,68,1,0,1,0,6,0,0,0.0,0,3
user = 0,2730,2048,238,500,20,4/3,4,0/1,16,0,1,1,1,-12,-11,-13,0,0,0,0,3,0,0,16,16,16,1,11,68,1,0,1,0,6,0,0,0.0,0,3
