[main]
orig_preset_name = Pocket_Genesis_DAR_9x_Fill.ini
display_name = auto-sampled.
description = Description can go here
tags = Comma separated list of tags, e.g. N64,320x240
; orig_feature_mask = 0x0500c77f

[scaler]
zoom_factor = fill
aspect_ratio = auto
horiz_kernel = sharper_alt
vert_kernel = sharper_alt
nn_auto_mode = on

[auto-sample]
context = *
expected = 1,+0,+0,+0,+0,-,-,1/1
expected = 4,+320,+92,-640,-184,64/49,-,4/1
expected = 5,+320,+92,-640,-184,64/49,-,4/1
method = 1
threshold = -1
