[main]
orig_preset_name = Analogue Pocket - SNES auto- sampled
display_name = Analogue Pocket - SNES auto- sampled
description = Description can go here
tags = analogue, pocket, snes, auto-sample
; orig_feature_mask = 0x7fffffff

[scaler]
zoom_factor = under
aspect_ratio = auto
horiz_kernel = sharper
vert_kernel = sharper
nn_auto_mode = on

[rx]
; Only used on Morph4K
input_cs = auto
edid_file = default.bin
fxd_mode = on
dv1_mode = on
ena_422_interp = yes
skip_422_derep = no
md.enabled = no
md.detect.spd_name = 
md.detect.width = 0
md.detect.height = 0
md.offsets.left = 160
md.offsets.right = -160
md.offsets.top = 40
md.offsets.bottom = -40
md.prescale.h = 4
md.prescale.v = 4/1
md.ar = 3/2
md.ign_aviif_pr = no


[auto-sample]
context = *
expected = 1,+0,+0,+0,+0,16/9,-,1/1
expected = 2,+448,+92,-896,-184,4/3,-,-
expected = 4,+448,+92,-896,-184,4/3,-,-
method = 1
threshold = -1
